export const FORM_LABELS = {
    deleteTooltip: 'Удалить задачу',
    add: 'Добавить',
    addTooltip: 'Добавить задачу',
    save: 'Сохранить',
    makeProgressing: 'Перенести в действующие',
    makeCompleted: 'Перенести в завершенные',
    addPlaceholder: 'Введите новую задачу',
    addDescriptionPlaceholder: 'Введите описание задачи',
    listItemTooltip: 'Кликните, справа появится описание задачи',
    addSuccess: 'Задача добавлена успешно!',
    addError: 'Ошибка при добавлении задачи!',
    deleteSuccess: 'Задача удалена успешно!',
    deleteError: 'Ошибка при удалении задачи!',
    updateSuccess: 'Задача обновлена успешно!',
    updateError: 'Ошибка при обновлении задачи!',
    changeStatusSuccess: 'Статус задачи изменен!',
    titleRequired: 'Название задачи обязательно',
    minLengthTitle: 'Минимальная длина: 3 символа',
    newTaskFormTitle: 'Создание новой задачи',
    noTasks: 'Нет задач',
};
