export const FORM_LABELS = {
    deleteTooltip: 'Удалить задачу',
    add: 'Добавить',
    addTooltip: 'Добавить задачу',
    save: 'Сохранить',
    addPlaceholder: 'Введите новую задачу',
    addDescriptionPlaceholder: 'Введите описание задачи',
    listItemTooltip: 'Кликните, справа появится описание задачи',
    addSuccess: 'Задача добавлена успешно!',
    deleteSuccess: 'Задача удалена успешно!',
    updateSuccess: 'Задача обновлена успешно!',
    changeStatusSuccess: 'Статус задачи изменен!',
    titleRequired: 'Название задачи обязательно',
    minLengthTitle: 'Минимальная длина: 3 символа',
};
